Произошла ошибка, почини её:
SyntaxError: The requested module '/node_modules/.vite/deps/web-vitals.js?v=e9d7a2a8' does not provide an export named 'onFID'